name: Apply changes to the server
run-name: ${{ github.actor }} is running the workflow
on: [push]
jobs:
    deploy-fe:
        runs-on: ubuntu-latest
        environment: correctable-lecture-translator
        steps:
            - name: Copy newest changes to the server
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                  cd ${{ secrets.WORK_DIR }}-prod
                  git checkout FrontendUpdates
                  git pull origin FrontendUpdates
                  cd frontend && npm install
